default_platform(:ios)

setup_travis
cocoapods(
  podfile: "./Example/Podfile",
  try_repo_update_on_error: true,
  silent: true
)

platform :ios do

  desc "Linting..."
  lane :linting do
    swiftlint(
      mode: :lint,
      executable: "Example/Pods/SwiftLint/swiftlint",
      config_file: ".swiftlint.yml",
      quiet: true
    )
    
    pod_lib_lint(
      verbose: true,
      quick: true
    )
  end

  desc "Linting and fixing..."
  lane :linting_fixing do
    swiftlint(
      mode: :autocorrect,
      executable: "Example/Pods/SwiftLint/swiftlint",
      config_file: ".swiftlint.yml"
    )
  end

  desc "Run tests for PredicateFlow (Debug config)"
  lane :test_debug do
    run_tests
  end

  desc "Run tests for PredicateFlow (Release config)"
  lane :test_release do
    run_tests

    xcov(
      workspace: "Example/PredicateFlow.xcworkspace",
      scheme: "PredicateFlow-Example",
      html_report: false,
      json_report: false,
      markdown_report: true,
      derived_data_path: "./build"
    )
  end

  desc "Create documentation"
  lane :documentation do
    jazzy(
      config: ".jazzy.yaml"
    )
    
    version = read_podspec['version']
    branch = git_branch
    
    git_add(path: "docs")
    git_commit(
      path: "docs",
      message: "Update docs folder for version #{version}"
    )
    push_to_git_remote(
      local_branch: branch,
      remote_branch: branch
    )
  end

  desc "Deploy to Cocoapods and push tag to master"
  lane :deploy do
    version = read_podspec['version']
    add_git_tag(tag: version)
    push_git_tags
    
    pod_push
  end
end
